version: 0.5.0.0
github: tek/helic
license: BSD-2-Clause-Patent
license-file: LICENSE
author: Torsten Schmits
maintainer: hackage@tryp.io
copyright: 2021 Torsten Schmits
category: Clipboard
build-type: Simple
